apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo
  namespace: default

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: java-demo

  template:
    metadata:
      labels:
        app: java-demo

    spec:
      containers:

      - name: java-demo
        image: naveen352/java-demo:latest

        ports:
        - containerPort: 8081

        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20


---
apiVersion: v1
kind: Service
metadata:
  name: java-demo-service
  namespace: default
spec:
  selector:
    app: java-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
  type: NodePort
